' math.bas
' Assemblied with PBC
' Copyright © 2018年 jadestudio. All rights reserved.

hehe:

TYPE DATE
    YEAR AS INTEGER
    MONTH AS INTEGER
    DATE AS INTEGER
END TYPE

TYPE TIME
    DATE AS DATE
    HOUR AS INTEGER
    MINUTE AS INTEGER
    SECOND AS INTEGER
END TYPE

DIM t1 AS TIME
DIM t2 AS TIME
DIM t3(2) AS TIME

IF (t1.DATE.YEAR MOD 4=0 AND t1.DATE.YEAR MOD 100<>0) OR t1.DATE.YEAR MOD 400=0 THEN
    PRINT "LEAP"
END IF

DECLARE FUNCTION ABS(num AS DOUBLE) AS DOUBLE

' ABS
FUNCTION ABS(num AS DOUBLE) AS DOUBLE
    IF (num < 0) THEN
        ABS = -num
    ELSE
        ABS = num
    END IF
END FUNCTION


DECLARE SUB STUN(a AS STRING, b AS INTEGER)

DIM C(-1 TO 1,3) AS INTEGER = {{222,222,2},{111,22,111},{2,6,2}}
ABS(1)


DIM s1 = "HELLO WORD"
DIM b()={{"A","B","C"},{"1","2","3"}}

IF b(1,2) = "HEHE" THEN
END IF

GOTO hehe

IF s1 <> "HELLO WORD" THEN
    REM DO SOMETHING
END IF

STUN ("test", 1)
